name: flutter_event_bus
description: |
  A library to provide EventBus and Interactor to Flutter app.
  It enables developer to write flutter app with Interactor pattern.
version: 0.0.3
homepage: https://github.com/timnew/flutter_event_bus/
repository: https://github.com/timnew/flutter_event_bus/

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  mockito: ^4.1.1

flutter:
